@startuml
'https://plantuml.com/component-diagram

[Class Diagram] --> [Intermediate]

[Intermediate] --> [Generate]
[Generate] --> [Source Code]

[Activity Diagram] -->  [Intermediate]
[Sequence Diagram] -->  [Intermediate]
[Description] -->  [Intermediate]

[Class Diagram]  --> [Description]
[Activity Diagram] -->  [Description]
[Sequence Diagram] -->  [Description]

@enduml